services:
  app:
    container_name: app
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/test?sslmode=disable
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    networks:
      - backend
    links:
      - database
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - '5433:5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
