version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    cmds:
      - go build -o app ./src/app.go
  build:image:prod:
    desc: Build production image using Dockerfile.prod and production ignore file
    cmds:
      - docker build -f Dockerfile.prod --ignorefile .dockerignore.prod -t url-shortener:prod .
  build:image:prod-nc:
    desc: Build production image without cache
    cmds:
      - docker build --no-cache -f Dockerfile.prod --ignorefile .dockerignore.prod -t url-shortener:prod .
  db:create-migration:
    cmds:
      - source load-envs && atlas migrate diff --env gorm
  db:migrate:
    cmds:
      - source load-envs && echo $DATABASE_URL && atlas migrate apply --env gorm
  install-atlas:
    cmds:
      - curl -sSf https://atlasgo.sh | sh